---
- name: Run Discovery Scan
  hosts: all
  gather_facts: no
  tasks:
    - name: Verify Sudo Access
      command: whoami
      become: yes
      register: sudo_check
      ignore_unreachable: yes
      ignore_errors: yes

    - name: Clear old group and add current survivors
      add_host:
        name: "{{ inventory_hostname }}"
        groups: active_targets
      when: sudo_check is success

- name: Generate Clean Inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create inventory.ini
      copy:
        dest: "./inventory/inventory.ini"
        content: |
          [active]
          {% for host in groups.get('active_targets', []) %}
          {{ host }}
          {% endfor %}